version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/dev.db
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
