version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - ./prisma:/app/prisma
      - sqlite_data:/app/data
    user: "1001:1001"  # Correspond à l'utilisateur nextjs créé dans le Dockerfile
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
